[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["cd backend && yarn install --frozen-lockfile"]

[phases.build]
cmds = ["cd backend && yarn build"]

[start]
cmd = "node dist/server.js"
