[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixos-23.05.tar.gz"

[phases.build]
cmd = "npm run build"
working_directory = "backend"

[start]
cmd = "node dist/server.js"
working_directory = "backend"
