[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmd = "yarn run build:shared && yarn run build"

[start]
cmd = "node dist/server.js"
