[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["cd backend && yarn install --frozen-lockfile"]

[phases.build]
cmd = "npm install && npm run build"

[start]
cmd = "node dist/server.js"
